# Generated by Django 5.2.4 on 2025-07-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_chat_id",
            field=models.BigIntegerField(
                blank=True,
                help_text="Chat ID пользователя Telegram для отправки уведомлений",
                null=True,
                verbose_name="Telegram Chat ID",
            ),
        ),
    ]
